version: '3.7'

services:
  miniconda:
    image: continuumio/miniconda3
    container_name: miniconda
    restart: always
    ports:
      - "8888:8888"
    networks:
      - duck

networks: 
  duck:
    driver: bridge