version: '3.7'

services:
  miniconda:
    image: continuumio/miniconda3
    container_name: miniconda
    restart: always
    command: bash conda "/opt/conda/bin/conda install jupyter -y --quiet && mkdir /opt/notebooks && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
    ports:
      - "8888:8888"
    networks:
      - duck

networks: 
  duck:
    driver: bridge