version: '3.7'

services:
  arangodb:
    image: arangodb
    container_name: arangodb
    restart: always
    environment:
      - ARANGO_RANDOM_ROOT_PASSWORD=1
    ports:
      - "8529:8529"
    networks: 
      - duck

networks: 
  duck:
    driver: bridge