version: '3.7'

services:

  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    env_file:
      - env/postgresql.env
    ports:
      - "5432:5432"
    networks: 
      - duck

  postgresql-adminer:
    image: adminer
    container_name: postgresql-adminer
    restart: always
    ports:
      - "8085:8080"
    networks: 
      - duck

networks: 
  duck:
    driver: bridge