version: '3.7'

services:
  nifi:
    image: apache/nifi:1.8.0
    container_name: nifi
    restart: always
    ports:
      - "8080:8080"
    networks: 
      - duck

networks: 
  duck:
    driver: bridge