version: '3.7'

services:

  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.1
    container_name: logstash
    restart: on-failure
    volumes:
      - volumes/logstash/pipeline:/usr/share/logstash/pipeline
      - volumes/logstash/output-templates:/usr/share/logstash/output_templates
      - volumes/logstash/enrichments/cti:/usr/share/logstash/cti
      - volumes/logstash/scripts:/usr/share/logstash/scripts
    entrypoint: /usr/share/logstash/scripts/logstash-entrypoint.sh
    ports:
      - "5044:5044"
      - "8531:8531"
    networks: duck

networks: 
  - duck