version: '3.7'

services:

  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.1
    container_name: logstash
    restart: on-failure
    entrypoint: /usr/share/logstash/scripts/logstash-entrypoint.sh
    ports:
      - "5044:5044"
      - "8531:8531"
    networks:
      - duck

networks: 
  duck:
    driver: bridge