version: '3.7'

services:
  prestosql:
    image: starburstdata/presto
    container_name: prestosql
    restart: always
    ports:
      - "8086:8080"
    networks: 
      - duck

networks: 
  duck:
    driver: bridge