version: '3.7'

services:
  couchbase:
    image: couchbase
    container_name: couchbase
    restart: on-failure
    ports:
      - "8091:8091"
      - "8096:8096"
      - "11210:11210"
      - "11211:11211"
    networks: duck

networks: 
  - duck