version: '3.7'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks: 
      - duck

networks: 
  duck:
    driver: bridge
