version: '3.7'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootexampple
      MONGO_INITDB_ROOT_PASSWORD: example
    networks: duck

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootexample
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks: duck

networks: 
  - duck