version: '3.7'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootexampple
      MONGO_INITDB_ROOT_PASSWORD: example
    networks: 
      - duck

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8082:8080"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootexample
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks: 
      - duck

networks: 
  duck:
    driver: bridge