version: '3.7'

services:
  anaconda:
    image: continuumio/anaconda3
    container_name: anaconda
    restart: always
    ports:
      - "8888:8888"
    networks: 
      - duck

networks: 
  duck:
    driver: bridge